name: Exécuter boucleyoutube

on:
  schedule:
    - cron: "0 19 * * *"  # Tous les jours à 19h
  workflow_dispatch:  # Exécution manuelle

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install pandas  # Installation de pandas
      
      - name: Run script
        run: python boucleyoutube.py > output.log 2>&1
      
      - name: Send email notification
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
          RECIPIENT: "homeart97200@gmail.com"
        run: |
          sudo apt-get install -y msmtp
          echo "account default" > ~/.msmtprc
          echo "host $SMTP_SERVER" >> ~/.msmtprc
          echo "port $SMTP_PORT" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user $SMTP_USER" >> ~/.msmtprc
          echo "password $SMTP_PASS" >> ~/.msmtprc
          echo "from $SMTP_USER" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Envoyer l'email
        run: |
          echo -e "Subject: Rapport Quotidien\n\nLe script s'est exécuté avec succès." | msmtp --file=report.log ${{ secrets.EMAIL_TO }}
          
